### ISSUE TITLE
ComponentStarter exit question/problem

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/core#21] opened 2018-05-03 07:42 UTC
Hi! 

I have noticed, that [ComponentStarter](https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/run/ComponentStarter.java) does the `System.exit()` only in case of unsuccess. 
In case of success Java remains working in docker container after the close() methods were executed. And docker containers are not terminating (nor locally, nor in the platform) and benchmark was stabily hangs up. The only possible way to terminate container - throw an error in close() method, which is a hack. `System.exit(0)` in close() didn't helped.

I have reproduced the problem in multiple components (taskGen, evalStorage, sysAdapter) - all were built by SDK with use of ComponentStarter from the core. Then I added System.exit(0) in case of success - it started to finish fine. The tricky thing, that standard (unmodified) version somehow worked for me in several benchmarks until yesterday :) maybe because of improper of usage standard waiting methods of AbstractBenchmarkController.

Also I would like to propose to move the `closeComponent();` into the `try` - just after run. Otherwise sometimes DataReceivers in components are failing to close quietly and it fill logs with tons of such errors - e.g. in Idea it is not possible to see previous log messages because of there ones.

**Comment by MichaelRoeder** [comment] 2018-05-07 15:09
This effect is already known for components which do not close all of their threads, correctly. The JVM is not stopping because it still has running threads that are not marked as daemon threads - so the JVM will wait for them to terminate. Typically, this is caused by a non-terminated thread pool. We encountered a problem like that before (#42). The workaround can be seen at https://github.com/hobbit-project/DataStorageBenchmark/commit/ca68647665c4f4259ef4b6bb362b7238afedf6dd
So in summary: yes, the `System.exit(0)` is working. However, it is only "hiding" that not all resources are freed, correctly.

The `closeComponent();` is located in the `finally` blog to make sure that it is always called - even if the `try` block is left with an exception. Yes, in case of an error this may lead to even more exceptions but it is better to try to close connections which are not there than leaving the program (and even other components to which it is connected) with resources that haven't been freed. :thinking:

**Comment by smirnp** [comment] 2018-05-07 16:16
Thanks!

**Closed as completed** 2019-10-18 09:17 UTC
